//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace CreditDashboard.Api.Contract
{
    using System = global::System;

    

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Money
    {

        /// <summary>
        /// Minor units (pence). Negative means a credit balance.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("amountMinor")]
        public int AmountMinor { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("currency")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<MoneyCurrency>))]
        public MoneyCurrency Currency { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum Sentiment
    {

        [System.Runtime.Serialization.EnumMember(Value = @"positive")]
        Positive = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"neutral")]
        Neutral = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"negative")]
        Negative = 2,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum AccountType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"creditcard")]
        Creditcard = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"loan")]
        Loan = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"mortgage")]
        Mortgage = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"currentaccount")]
        Currentaccount = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"telecomsandutilities")]
        Telecomsandutilities = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"lineofcredit")]
        Lineofcredit = 5,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum AccountStatus
    {

        [System.Runtime.Serialization.EnumMember(Value = @"normal")]
        Normal = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"arrears")]
        Arrears = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"default")]
        Default = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"settled")]
        Settled = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"closed")]
        Closed = 4,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum PaymentStatus
    {

        [System.Runtime.Serialization.EnumMember(Value = @"on-time")]
        OnTime = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"missed")]
        Missed = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"no-data")]
        NoData = 2,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum Persona
    {

        [System.Runtime.Serialization.EnumMember(Value = @"excellent")]
        Excellent = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"struggling")]
        Struggling = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"thin-file")]
        ThinFile = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"boundary")]
        Boundary = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"drilldown")]
        Drilldown = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"error")]
        Error = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"slow")]
        Slow = 6,

    }

    /// <summary>
    /// A defect that test control can switch on (DR-008). The API flags are in API specification section 10; the UI and profile flags are in the UI specification section 8 and the My Profile feature specification. A name outside this list is a 400, so a typo cannot silently do nothing.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum BugFlag
    {

        [System.Runtime.Serialization.EnumMember(Value = @"excluded-in-total")]
        ExcludedInTotal = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"rounding-down")]
        RoundingDown = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"history-carry-forward")]
        HistoryCarryForward = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"idor")]
        Idor = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"problem-json-missing")]
        ProblemJsonMissing = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"mask-format")]
        MaskFormat = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"currency-float")]
        CurrencyFloat = 6,

        [System.Runtime.Serialization.EnumMember(Value = @"duplicate-nav")]
        DuplicateNav = 7,

        [System.Runtime.Serialization.EnumMember(Value = @"util-mismatch")]
        UtilMismatch = 8,

        [System.Runtime.Serialization.EnumMember(Value = @"currency-format")]
        CurrencyFormat = 9,

        [System.Runtime.Serialization.EnumMember(Value = @"minor-units-label")]
        MinorUnitsLabel = 10,

        [System.Runtime.Serialization.EnumMember(Value = @"placeholder-aria")]
        PlaceholderAria = 11,

        [System.Runtime.Serialization.EnumMember(Value = @"chart-no-values")]
        ChartNoValues = 12,

        [System.Runtime.Serialization.EnumMember(Value = @"range-stale")]
        RangeStale = 13,

        [System.Runtime.Serialization.EnumMember(Value = @"toggle-label")]
        ToggleLabel = 14,

        [System.Runtime.Serialization.EnumMember(Value = @"like-both")]
        LikeBoth = 15,

        [System.Runtime.Serialization.EnumMember(Value = @"plural")]
        Plural = 16,

        [System.Runtime.Serialization.EnumMember(Value = @"button-href")]
        ButtonHref = 17,

        [System.Runtime.Serialization.EnumMember(Value = @"double-render")]
        DoubleRender = 18,

        [System.Runtime.Serialization.EnumMember(Value = @"ph-a11y")]
        PhA11y = 19,

        [System.Runtime.Serialization.EnumMember(Value = @"open-redirect")]
        OpenRedirect = 20,

        [System.Runtime.Serialization.EnumMember(Value = @"truncate-summary")]
        TruncateSummary = 21,

        [System.Runtime.Serialization.EnumMember(Value = @"negative-balance")]
        NegativeBalance = 22,

        [System.Runtime.Serialization.EnumMember(Value = @"nested-button")]
        NestedButton = 23,

        [System.Runtime.Serialization.EnumMember(Value = @"decorative-alt")]
        DecorativeAlt = 24,

        [System.Runtime.Serialization.EnumMember(Value = @"preferred-on-report")]
        PreferredOnReport = 25,

        [System.Runtime.Serialization.EnumMember(Value = @"preferred-no-trim")]
        PreferredNoTrim = 26,

        [System.Runtime.Serialization.EnumMember(Value = @"email-stays-verified")]
        EmailStaysVerified = 27,

        [System.Runtime.Serialization.EnumMember(Value = @"pii-in-title")]
        PiiInTitle = 28,

        [System.Runtime.Serialization.EnumMember(Value = @"lost-edit")]
        LostEdit = 29,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum VerificationStatus
    {

        [System.Runtime.Serialization.EnumMember(Value = @"verified")]
        Verified = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"unverified")]
        Unverified = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum EmploymentStatus
    {

        [System.Runtime.Serialization.EnumMember(Value = @"employed-full-time")]
        EmployedFullTime = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"employed-part-time")]
        EmployedPartTime = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"self-employed")]
        SelfEmployed = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"unemployed")]
        Unemployed = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"retired")]
        Retired = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"student")]
        Student = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"other")]
        Other = 6,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Profile
    {

        /// <summary>
        /// Read-only in the app (PR-01)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("legalName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string LegalName { get; set; }

        /// <summary>
        /// Read-only in the app (PR-01)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("dateOfBirth")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTimeOffset DateOfBirth { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("memberSince")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTimeOffset MemberSince { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("preferredName")]
        public string PreferredName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("email")]
        [System.ComponentModel.DataAnnotations.Required]
        public EmailContact Email { get; set; } = new EmailContact();

        /// <summary>
        /// Null when no number is held. Only the last three digits leave the service.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("mobile")]
        public MobileContact Mobile { get; set; }

        /// <summary>
        /// Current address summary; null when none is held
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("address")]
        public Address Address { get; set; }

        /// <summary>
        /// Null when not added
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("employment")]
        public Employment Employment { get; set; }

        /// <summary>
        /// Whether finance details are held; never the figures (PR-07)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("finances")]
        [System.ComponentModel.DataAnnotations.Required]
        public Finances Finances { get; set; } = new Finances();

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class EmailContact
    {

        [System.Text.Json.Serialization.JsonPropertyName("address")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Address { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<VerificationStatus>))]
        public VerificationStatus Status { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class EmailChange
    {

        [System.Text.Json.Serialization.JsonPropertyName("address")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(254)]
        public string Address { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class VerificationSent
    {

        [System.Text.Json.Serialization.JsonPropertyName("sentAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset SentAt { get; set; }

        /// <summary>
        /// sentAt plus 60 seconds (PR-09)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("nextResendAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset NextResendAt { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class MobileContact
    {

        [System.Text.Json.Serialization.JsonPropertyName("lastDigits")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^[0-9]{3}$")]
        public string LastDigits { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<VerificationStatus>))]
        public VerificationStatus Status { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class MobileChange
    {

        /// <summary>
        /// Checked against PR-06 by the service (422)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("number")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(20, MinimumLength = 1)]
        public string Number { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class MobileChallenge : MobileContact
    {

        /// <summary>
        /// Issue time plus 10 minutes (PR-10)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("expiresAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset ExpiresAt { get; set; }

        /// <summary>
        /// PR-11
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("attemptsRemaining")]
        [System.ComponentModel.DataAnnotations.Range(0, 3)]
        public int AttemptsRemaining { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class MobileVerification
    {

        [System.Text.Json.Serialization.JsonPropertyName("code")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^[0-9]{6}$")]
        public string Code { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PreferredNameUpdate
    {

        /// <summary>
        /// Raw input; trimmed by the service before PR-02 is applied
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("preferredName")]
        [System.ComponentModel.DataAnnotations.StringLength(100)]
        public string PreferredName { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PreferredName
    {

        [System.Text.Json.Serialization.JsonPropertyName("preferredName")]
        public string PreferredName1 { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class LoginRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("username")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Username { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("password")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Password { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class LoginResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("token")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Token { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("expiresAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset ExpiresAt { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class User
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Id { get; set; }

        /// <summary>
        /// The legal name
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("displayName")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string DisplayName { get; set; }

        /// <summary>
        /// The name the app greets the customer by (PR-03): the preferred name when set, otherwise the first word of the legal name (DR-036).
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("greetingName")]
        [System.ComponentModel.DataAnnotations.Required]
        public string GreetingName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("defaultBureauId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string DefaultBureauId { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Bureau
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Name { get; set; }

        /// <summary>
        /// BR-08
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("nextUpdateInDays")]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int NextUpdateInDays { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Score
    {

        [System.Text.Json.Serialization.JsonPropertyName("current")]
        [System.ComponentModel.DataAnnotations.Range(0, 1000)]
        public int Current { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("max")]
        public int Max { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("nationalAverage")]
        [System.ComponentModel.DataAnnotations.Range(0, 1000)]
        public int NationalAverage { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("localAverage")]
        [System.ComponentModel.DataAnnotations.Range(0, 1000)]
        public int LocalAverage { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ScorePoint
    {

        [System.Text.Json.Serialization.JsonPropertyName("month")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^\d{4}-\d{2}$")]
        public string Month { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("score")]
        [System.ComponentModel.DataAnnotations.Range(0D, 1000D)]
        public int? Score { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Change
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("title")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Title { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("sentiment")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<Sentiment>))]
        public Sentiment Sentiment { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("impact")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<ChangeImpact>))]
        public ChangeImpact Impact { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("date")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTimeOffset Date { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ChangePage : PageMeta
    {

        [System.Text.Json.Serialization.JsonPropertyName("items")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<Change> Items { get; set; } = new System.Collections.ObjectModel.Collection<Change>();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Impact
    {

        [System.Text.Json.Serialization.JsonPropertyName("actionNeeded")]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int ActionNeeded { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("monitor")]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int Monitor { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("doingWell")]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int DoingWell { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Summary
    {

        [System.Text.Json.Serialization.JsonPropertyName("text")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Text { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("feedback")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<SummaryFeedback>))]
        public SummaryFeedback Feedback { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ReportOverview
    {

        [System.Text.Json.Serialization.JsonPropertyName("bureau")]
        [System.ComponentModel.DataAnnotations.Required]
        public Bureau Bureau { get; set; } = new Bureau();

        [System.Text.Json.Serialization.JsonPropertyName("score")]
        [System.ComponentModel.DataAnnotations.Required]
        public Score Score { get; set; } = new Score();

        [System.Text.Json.Serialization.JsonPropertyName("summary")]
        [System.ComponentModel.DataAnnotations.Required]
        public Summary Summary { get; set; } = new Summary();

        [System.Text.Json.Serialization.JsonPropertyName("recentChanges")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.MaxLength(3)]
        public System.Collections.Generic.ICollection<Change> RecentChanges { get; set; } = new System.Collections.ObjectModel.Collection<Change>();

        [System.Text.Json.Serialization.JsonPropertyName("changesTotal")]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int ChangesTotal { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("impact")]
        [System.ComponentModel.DataAnnotations.Required]
        public Impact Impact { get; set; } = new Impact();

        [System.Text.Json.Serialization.JsonPropertyName("debt")]
        [System.ComponentModel.DataAnnotations.Required]
        public DebtOverview Debt { get; set; } = new DebtOverview();

        [System.Text.Json.Serialization.JsonPropertyName("accountTypes")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<AccountTotals> AccountTypes { get; set; } = new System.Collections.ObjectModel.Collection<AccountTotals>();

        /// <summary>
        /// onReport is the number of (account, month) pairs with status missed in the BR-12 window across the bureau's accounts; newMissed is those in the three months ending at the current month (decision brief 9 D4).
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("payments")]
        [System.ComponentModel.DataAnnotations.Required]
        public Payments Payments { get; set; } = new Payments();

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AccountSummary
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<AccountType>))]
        public AccountType Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("provider")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Provider { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("logoUrl")]
        public System.Uri LogoUrl { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("maskedNumber")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^\*[A-Z0-9]{4}$")]
        public string MaskedNumber { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("balance")]
        [System.ComponentModel.DataAnnotations.Required]
        public Money Balance { get; set; } = new Money();

        [System.Text.Json.Serialization.JsonPropertyName("limit")]
        public Money Limit { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("utilisation")]
        [System.ComponentModel.DataAnnotations.Range(0D, double.MaxValue)]
        public int? Utilisation { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("includedInTotals")]
        public bool IncludedInTotals { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<AccountStatus>))]
        public AccountStatus Status { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AccountTotals
    {

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<AccountType>))]
        public AccountType Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("balance")]
        [System.ComponentModel.DataAnnotations.Required]
        public Money Balance { get; set; } = new Money();

        [System.Text.Json.Serialization.JsonPropertyName("limit")]
        public Money Limit { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("utilisation")]
        [System.ComponentModel.DataAnnotations.Range(0D, double.MaxValue)]
        public int? Utilisation { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("includedCount")]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int IncludedCount { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("excluded")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<Excluded> Excluded { get; set; } = new System.Collections.ObjectModel.Collection<Excluded>();

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AccountDetails
    {

        [System.Text.Json.Serialization.JsonPropertyName("apr")]
        [System.ComponentModel.DataAnnotations.Range(0D, 100D)]
        public double? Apr { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("interestRate")]
        [System.ComponentModel.DataAnnotations.Range(0D, 100D)]
        public double? InterestRate { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("promoPeriodMonths")]
        [System.ComponentModel.DataAnnotations.Range(0D, 60D)]
        public int? PromoPeriodMonths { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("minPayment")]
        public MinPayment MinPayment { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("paymentMethod")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<AccountDetailsPaymentMethod>))]
        public AccountDetailsPaymentMethod? PaymentMethod { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Account : AccountSummary
    {

        [System.Text.Json.Serialization.JsonPropertyName("openedDate")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTimeOffset OpenedDate { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("closedDate")]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTimeOffset? ClosedDate { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("updateFrequency")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<AccountUpdateFrequency>))]
        public AccountUpdateFrequency UpdateFrequency { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("lastUpdated")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTimeOffset LastUpdated { get; set; }

        /// <summary>
        /// Unfloored value (BR-06)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("utilisationRaw")]
        public int? UtilisationRaw { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("details")]
        [System.ComponentModel.DataAnnotations.Required]
        public AccountDetails Details { get; set; } = new AccountDetails();

        [System.Text.Json.Serialization.JsonPropertyName("closed")]
        public bool Closed { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class DetailUpdate
    {

        [System.Text.Json.Serialization.JsonPropertyName("field")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<DetailUpdateField>))]
        public DetailUpdateField Field { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("value")]
        [System.ComponentModel.DataAnnotations.Required]
        public object Value { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class BalancePoint
    {

        [System.Text.Json.Serialization.JsonPropertyName("month")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^\d{4}-\d{2}$")]
        public string Month { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("balance")]
        [System.ComponentModel.DataAnnotations.Required]
        public Money Balance { get; set; } = new Money();

        [System.Text.Json.Serialization.JsonPropertyName("limit")]
        public Money Limit { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// An account as source data (API spec section 9.1): the contract Account plus the inputs the service derives from. Used by persona fixtures and by test-control overrides (DR-020).
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FixtureAccount : Account
    {

        /// <summary>
        /// BR-09 input as the source supplies it
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("sourceMask")]
        [System.ComponentModel.DataAnnotations.StringLength(int.MaxValue, MinimumLength = 1)]
        public string SourceMask { get; set; }

        /// <summary>
        /// BR-12 source
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("missedMonths")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<string> MissedMonths { get; set; } = new System.Collections.ObjectModel.Collection<string>();

        /// <summary>
        /// Oldest first; also the BR-07 trend source
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("balanceHistory")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.MaxLength(6)]
        public System.Collections.Generic.ICollection<BalancePoint> BalanceHistory { get; set; } = new System.Collections.ObjectModel.Collection<BalancePoint>();

    }

    /// <summary>
    /// Test-control data for one binding (DR-020). Each list named for a bureau replaces that list; lists not named are kept from the persona.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PersonaOverrides
    {

        [System.Text.Json.Serialization.JsonPropertyName("bureaux")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.MinLength(1)]
        public System.Collections.Generic.ICollection<Bureaux> Bureaux { get; set; } = new System.Collections.ObjectModel.Collection<Bureaux>();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PaymentHistory
    {

        [System.Text.Json.Serialization.JsonPropertyName("years")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.MinLength(7)]
        [System.ComponentModel.DataAnnotations.MaxLength(7)]
        public System.Collections.Generic.ICollection<Years> Years { get; set; } = new System.Collections.ObjectModel.Collection<Years>();

        [System.Text.Json.Serialization.JsonPropertyName("selectedYear")]
        public int SelectedYear { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("missed")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<Missed> Missed { get; set; } = new System.Collections.ObjectModel.Collection<Missed>();

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Search
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("kind")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<SearchKind>))]
        public SearchKind Kind { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("organisation")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Organisation { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("purpose")]
        public string Purpose { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("date")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTimeOffset Date { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SearchPage : PageMeta
    {

        [System.Text.Json.Serialization.JsonPropertyName("items")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<Search> Items { get; set; } = new System.Collections.ObjectModel.Collection<Search>();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PersonalDetails
    {

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("addresses")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<Addresses> Addresses { get; set; } = new System.Collections.ObjectModel.Collection<Addresses>();

        [System.Text.Json.Serialization.JsonPropertyName("electoralRoll")]
        public bool ElectoralRoll { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class DebtOverview
    {

        [System.Text.Json.Serialization.JsonPropertyName("total")]
        [System.ComponentModel.DataAnnotations.Required]
        public Money Total { get; set; } = new Money();

        /// <summary>
        /// The total split by account type (BR-07, DR-046): for each type, the sum of positive balances of open accounts with includedInTotals true. One entry per type whose sum is above zero, in AccountType enum order; current accounts never appear. The entries sum to total.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("byType")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<ByType> ByType { get; set; } = new System.Collections.ObjectModel.Collection<ByType>();

        /// <summary>
        /// Against total debt three months earlier (BR-07). Steady when the unrounded change is at most 1% either way; if the earlier total was zero, steady when now zero, otherwise up (DR-011).
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("trend")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<DebtOverviewTrend>))]
        public DebtOverviewTrend Trend { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Notification
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("title")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Title { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("read")]
        public bool Read { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset CreatedAt { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class NotificationPage : PageMeta
    {

        [System.Text.Json.Serialization.JsonPropertyName("items")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<Notification> Items { get; set; } = new System.Collections.ObjectModel.Collection<Notification>();

        [System.Text.Json.Serialization.JsonPropertyName("unread")]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int Unread { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Feedback
    {

        [System.Text.Json.Serialization.JsonPropertyName("value")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<FeedbackValue>))]
        public FeedbackValue Value { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PageMeta
    {

        [System.Text.Json.Serialization.JsonPropertyName("page")]
        [System.ComponentModel.DataAnnotations.Range(1, int.MaxValue)]
        public int Page { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("pageSize")]
        [System.ComponentModel.DataAnnotations.Range(1, int.MaxValue)]
        public int PageSize { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("total")]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int Total { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Problem
    {

        /// <summary>
        /// The problem type (API specification section 8). A 422 names its rule outcome under /problems/rule-violation/ (DR-048); clients and tests branch on type, never on title or detail.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("title")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Title { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        public int Status { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("detail")]
        public string Detail { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("instance")]
        public string Instance { get; set; }

        /// <summary>
        /// code-wrong only (PR-11); code-invalid carries none
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("attemptsRemaining")]
        [System.ComponentModel.DataAnnotations.Range(0, 3)]
        public int AttemptsRemaining { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("errors")]
        public System.Collections.Generic.ICollection<Errors> Errors { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum Range
    {

        [System.Runtime.Serialization.EnumMember(Value = @"3m")]
        _3m = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"6m")]
        _6m = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"1y")]
        _1y = 2,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum Kind
    {

        [System.Runtime.Serialization.EnumMember(Value = @"hard")]
        Hard = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"soft")]
        Soft = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum Status
    {

        [System.Runtime.Serialization.EnumMember(Value = @"open")]
        Open = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"closed")]
        Closed = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Body
    {

        [System.Text.Json.Serialization.JsonPropertyName("read")]
        public bool Read { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Body2
    {

        [System.Text.Json.Serialization.JsonPropertyName("message")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(500, MinimumLength = 1)]
        public string Message { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Body3
    {

        [System.Text.Json.Serialization.JsonPropertyName("persona")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<Persona>))]
        public Persona Persona { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("overrides")]
        public PersonaOverrides Overrides { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Body4
    {

        [System.Text.Json.Serialization.JsonPropertyName("flags")]
        // TODO(system.text.json): Add ItemConverterType with enum converter when supported
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<BugFlag> Flags { get; set; } = new System.Collections.ObjectModel.Collection<BugFlag>();

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Body5
    {

        [System.Text.Json.Serialization.JsonPropertyName("now")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset Now { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Body6
    {

        [System.Text.Json.Serialization.JsonPropertyName("fixedMs")]
        [System.ComponentModel.DataAnnotations.Range(0, 10000)]
        public int FixedMs { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("minMs")]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int MinMs { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("maxMs")]
        [System.ComponentModel.DataAnnotations.Range(int.MinValue, 10000)]
        public int MaxMs { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Body7
    {

        [System.Text.Json.Serialization.JsonPropertyName("username")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Username { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Response
    {

        [System.Text.Json.Serialization.JsonPropertyName("reply")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Reply { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("disclaimer")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Disclaimer { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Response2
    {

        [System.Text.Json.Serialization.JsonPropertyName("personas")]
        public System.Collections.Generic.IDictionary<string, Persona> Personas { get; set; }

        /// <summary>
        /// Whether each bound user has overrides in force (DR-020)
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("overridden")]
        public System.Collections.Generic.IDictionary<string, bool> Overridden { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("flags")]
        // TODO(system.text.json): Add ItemConverterType with enum converter when supported
        public System.Collections.Generic.ICollection<BugFlag> Flags { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("now")]
        public System.DateTimeOffset? Now { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("latency")]
        public object Latency { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum MoneyCurrency
    {

        [System.Runtime.Serialization.EnumMember(Value = @"GBP")]
        GBP = 0,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Address
    {

        [System.Text.Json.Serialization.JsonPropertyName("line1")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Line1 { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("postcode")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Postcode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("previousCount")]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int PreviousCount { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Employment
    {

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<EmploymentStatus>))]
        public EmploymentStatus Status { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Finances
    {

        [System.Text.Json.Serialization.JsonPropertyName("added")]
        public bool Added { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum ChangeImpact
    {

        [System.Runtime.Serialization.EnumMember(Value = @"low")]
        Low = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"medium")]
        Medium = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"high")]
        High = 2,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum SummaryFeedback
    {

        [System.Runtime.Serialization.EnumMember(Value = @"like")]
        Like = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"dislike")]
        Dislike = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"none")]
        None = 2,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Payments
    {

        [System.Text.Json.Serialization.JsonPropertyName("newMissed")]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int NewMissed { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("onReport")]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int OnReport { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Excluded
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("provider")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Provider { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("maskedNumber")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^\*[A-Z0-9]{4}$")]
        public string MaskedNumber { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("balance")]
        [System.ComponentModel.DataAnnotations.Required]
        public Money Balance { get; set; } = new Money();

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class MinPayment
    {

        [System.Text.Json.Serialization.JsonPropertyName("amount")]
        public Money Amount { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("percent")]
        [System.ComponentModel.DataAnnotations.Range(0D, 100D)]
        public double Percent { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum AccountDetailsPaymentMethod
    {

        [System.Runtime.Serialization.EnumMember(Value = @"direct-debit")]
        DirectDebit = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"manual")]
        Manual = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum AccountUpdateFrequency
    {

        [System.Runtime.Serialization.EnumMember(Value = @"monthly")]
        Monthly = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"quarterly")]
        Quarterly = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum DetailUpdateField
    {

        [System.Runtime.Serialization.EnumMember(Value = @"apr")]
        Apr = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"interestRate")]
        InterestRate = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"promoPeriodMonths")]
        PromoPeriodMonths = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"minPayment")]
        MinPayment = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"paymentMethod")]
        PaymentMethod = 4,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Bureaux
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("accounts")]
        public System.Collections.Generic.ICollection<FixtureAccount> Accounts { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("changes")]
        public System.Collections.Generic.ICollection<Change> Changes { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("searches")]
        public System.Collections.Generic.ICollection<Search> Searches { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Years
    {

        [System.Text.Json.Serialization.JsonPropertyName("year")]
        public int Year { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<PaymentStatus>))]
        public PaymentStatus Status { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Missed
    {

        [System.Text.Json.Serialization.JsonPropertyName("accountId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string AccountId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("provider")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Provider { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("month")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^\d{4}-\d{2}$")]
        public string Month { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum SearchKind
    {

        [System.Runtime.Serialization.EnumMember(Value = @"hard")]
        Hard = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"soft")]
        Soft = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Addresses
    {

        [System.Text.Json.Serialization.JsonPropertyName("line1")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Line1 { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("town")]
        public string Town { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("postcode")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Postcode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("current")]
        public bool Current { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ByType
    {

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<AccountType>))]
        public AccountType Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("amount")]
        [System.ComponentModel.DataAnnotations.Required]
        public Money Amount { get; set; } = new Money();

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum DebtOverviewTrend
    {

        [System.Runtime.Serialization.EnumMember(Value = @"up")]
        Up = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"down")]
        Down = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"steady")]
        Steady = 2,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum FeedbackValue
    {

        [System.Runtime.Serialization.EnumMember(Value = @"like")]
        Like = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"dislike")]
        Dislike = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"none")]
        None = 2,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Errors
    {

        [System.Text.Json.Serialization.JsonPropertyName("field")]
        public string Field { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("message")]
        public string Message { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    internal class DateFormatConverter : System.Text.Json.Serialization.JsonConverter<System.DateTimeOffset>
    {
        public override System.DateTimeOffset Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
        {
            var dateTime = reader.GetString();
            if (dateTime == null)
            {
                throw new System.Text.Json.JsonException("Unexpected JsonTokenType.Null");
            }

            return System.DateTimeOffset.Parse(dateTime);
        }

        public override void Write(System.Text.Json.Utf8JsonWriter writer, System.DateTimeOffset value, System.Text.Json.JsonSerializerOptions options)
        {
            writer.WriteStringValue(value.ToString("yyyy-MM-dd"));
        }
    }



    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ApiException : System.Exception
    {
        public int StatusCode { get; private set; }

        public string Response { get; private set; }

        public System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> Headers { get; private set; }

        public ApiException(string message, int statusCode, string response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Exception innerException)
            : base(message + "\n\nStatus: " + statusCode + "\nResponse: \n" + ((response == null) ? "(null)" : response.Substring(0, response.Length >= 512 ? 512 : response.Length)), innerException)
        {
            StatusCode = statusCode;
            Response = response;
            Headers = headers;
        }

        public override string ToString()
        {
            return string.Format("HTTP Response: \n\n{0}\n\n{1}", Response, base.ToString());
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ApiException<TResult> : ApiException
    {
        public TResult Result { get; private set; }

        public ApiException(string message, int statusCode, string response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, TResult result, System.Exception innerException)
            : base(message, statusCode, response, headers, innerException)
        {
            Result = result;
        }
    }

}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765